/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "random.h"

bool_t
xdr_messagecontent (XDR *xdrs, messagecontent *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->messagetype))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->matrikelnumber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->randomvalue))
		 return FALSE;
	return TRUE;
}
